//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oqtane.ChatHubs.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oqtane.ChatHubs.Server.Resources.CommandResources", typeof(CommandResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear;recycle;free;.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commands;list-commands;.
        /// </summary>
        public static string commands {
            get {
                return ResourceManager.GetString("commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnect;exit;shutdown;.
        /// </summary>
        public static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flicker;.
        /// </summary>
        public static string flicker {
            get {
                return ResourceManager.GetString("flicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ignore;block;.
        /// </summary>
        public static string ignore {
            get {
                return ResourceManager.GetString("ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invite;.
        /// </summary>
        public static string invite {
            get {
                return ResourceManager.GetString("invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me;myself;i;.
        /// </summary>
        public static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message-color;msg-color;.
        /// </summary>
        public static string message_color {
            get {
                return ResourceManager.GetString("message-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unignore;unblock;.
        /// </summary>
        public static string unignore {
            get {
                return ResourceManager.GetString("unignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username-color;.
        /// </summary>
        public static string username_color {
            get {
                return ResourceManager.GetString("username-color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whisper;asmr;.
        /// </summary>
        public static string whisper {
            get {
                return ResourceManager.GetString("whisper", resourceCulture);
            }
        }
    }
}
